name: Create Production Builds

on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build Android
    type: build
    platform: android
    profile: production

  build_ios:
    name: Build iOS
    type: build
    platform: ios
    profile: production
